### PR TITLE
Added Kotlin Get notifications, Get notification statistics, Get notification Examples for Notification API in API Reference Documentation

### PR DESCRIPTION
**Pull request by biplobsd**
Issues: #268

## Important
Those example files are empty. That is why they are auto-generated. By adding Kotlin code examples, other language examples are removed. https://mintlify.com/blog/autogenerate-openapi

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@biplobsd Will you be willing to add other languages? because we can't have only Kotlin there now. We need at least 4 languages to be there.

**Comment by biplobsd** [comment]
@unicodeveloper I refer @nabinbhatt for adding other languages.

**Comment by biplobsd** [comment]
https://biplobsd.me/blogs/view/contributing-to-open-source-my-hacktoberfest-experience.md

I wrote a blog about my hacktoberfest journey. I mentioned @sumitsaurabh927 and @unicodeveloper to on my blog.

**Comment by sumitsaurabh927** [comment]
> https://biplobsd.me/blogs/view/contributing-to-open-source-my-hacktoberfest-experience.md
> 
> I wrote a blog about my hacktoberfest journey. I mentioned @sumitsaurabh927 and @unicodeveloper to on my blog.

Thanks for the article Biplob! Just went through it and thoroughly enjoyed reading it. Good luck with everything you're doing! 🚀

**Comment by biplobsd** [comment]
> > https://biplobsd.me/blogs/view/contributing-to-open-source-my-hacktoberfest-experience.md
> > I wrote a blog about my hacktoberfest journey. I mentioned @sumitsaurabh927 and @unicodeveloper to on my blog.
> 
> Thanks for the article Biplob! Just went through it and thoroughly enjoyed reading it. Good luck with everything you're doing! 🚀

Thanks 🥹

**Comment by unicodeveloper** [comment]
@biplobsd Please can you resolve these conflicts?

**Comment by biplobsd** [comment]
@unicodeveloper review again

**Review by jainpawan21 — APPROVED** [review]
Thanks @biplobsd 🚀

**Pull request merged**
