### PR TITLE
docs: add smsmode provider documentation

### PR DESCRIPTION
**Pull request by nohira**

### CODE REVIEW

**Comment by jainpawan21** [comment]
@nohira Could you please steps needed from the provider side.

Take twilio as reference
https://docs.novu.co/channels-and-providers/sms/twilio#setting-up-twilio

**Review by jainpawan21 — CHANGES_REQUESTED** [review]
Add provider steps

**Comment by unicodeveloper** [comment]
@nohira Please, any updates here?

**Comment by nohira** [comment]
Is it better? Please tell me before I do modification on brevo provider.

**Comment by nohira** [comment]
Hi @unicodeveloper,

I've updated. I've added step by step guide for getting api key and sender information.

**Comment by unicodeveloper** [comment]
@nohira please is there a reason this is submitted to a 0.23.0 branch?

**Comment by nohira** [comment]
Hi @unicodeveloper ,

I made two PR for two providers for staging. It was moved to target 0.23.0. I guess it was for the same reason as brevo documentation

**Pull request merged**
