### PR TITLE
enhanced icons colors in SDK's and Quickstart

### PR DESCRIPTION
**Pull request by shelar1423**
# why this change ?
icons default color is not matching and was kept as diffrent color along side other icons which did not provide a clean look

before:
image
image

After:
image
image

### CODE REVIEW

**Comment by shelar1423** [comment]
@unicodeveloper kindly have a review

**Comment by unicodeveloper** [comment]
Thanks for the PR. Unfortunately, I won't accept this PR. We don't need to change the colors. They work just fine

**Comment by shelar1423** [comment]
@unicodeveloper sure

**Comment by michaldziuba03** [comment]
@unicodeveloper to be honest I would suggest to reconsider this PR.

There is any reason to not follow "brand" guidelines? Why Vue is blue and Angular green? For me personally it looks bad and not intuitively.

**Comment by unicodeveloper** [comment]
This is a good point. I'm a little skeptical because I don't want to encourage PRs that basically change icons or positions of items on the doc pages when there are other issues available to tackle @michaldziuba03 @shelar1423

**Comment by unicodeveloper** [comment]
@shelar1423 Are there other brand guidelines errors you found on the docs asides this?

**Comment by shelar1423** [comment]
@unicodeveloper yeah also I found an issue with the ruby and kotlin icon as they look totally different from other icons and their colors also can't be changed . I understand the color brand guidelines weren't a big thing but as a beginner with no code experience I thought to make it look appealing with the appropriate colors .

**Comment by shelar1423** [comment]
And also it does look awkward with the opposite colors ,if not this pr but i recommend it to be fixed for clean look

**Comment by shelar1423** [comment]
@unicodeveloper also the icon for  S3 can be kept as AWS as there is not proper icon given for S3 in side bar

**Comment by shelar1423** [comment]
hey @unicodeveloper are we going to reconsider this or want me to delete this fork and make a new one to make other chnages?

**Comment by unicodeveloper** [comment]
@shelar1423 I have reopened it. Can you add the other changes here and let me know?

**Comment by shelar1423** [comment]
@unicodeveloper done, have a look 
1.Added better colorful logo of kotlin and ruby
2.few places where the vue and angular colors were left to be replaced are replaced
3.In side bar icons added aws icon to s3

image
image

**Comment by shelar1423** [comment]
Hey @unicodeveloper please have a look and let me know as there is a leaderboard and being late to be merged might be an issue for me ,hope you understand,thanks you

**Comment by shelar1423** [comment]
@scopsy kindly have a review,thank you

**Review by unicodeveloper — APPROVED** [review]

**Comment by unicodeveloper** [comment]
We greatly appreciate your contribution. We hope you'll stay with us and continue to be an integral part of this project.

Please consider giving this repo a star and joining our community discord server, if you haven't already, to access more resources and connect with like-minded individuals. [Discord Community here 🎉 ](https://discord.gg/novu) #Hacktoberfest

**Pull request merged**
