### PR TITLE
Fixed spacing between element

### PR DESCRIPTION
**Pull request by biplobsd**
| Before      | After |
| ----------- | ----------- |
| image | image |
| image | image |
| image | image |
| image | image |

Page: https://docs.novu.co/getting-started/send-your-first-notification

### CODE REVIEW

**Comment by biplobsd** [comment]
@sumitsaurabh927 kindly take a review

**Comment by unicodeveloper** [comment]
Were you assigned an issue for this PR? @biplobsd

**Review by unicodeveloper — APPROVED** [review]

**Comment by biplobsd** [comment]
@unicodeveloper I'm sorry for not creating an issue. I am confident about this problem. Now I will create an issue first.

**Comment by biplobsd** [comment]
Hi, @unicodeveloper, is it possible that contributions without issues are not counted for Hacktoberfest? I only see a score of 1 on the leaderboard. #252 #256

Note:
For those pull requests, I need to learn how Muntlify works and understand what components it contains and the parameters associated with them. I need to know how to create space between elements. 😐

**Comment by unicodeveloper** [comment]
If your PR does not have a `Hacktoberfest` label, then it won't be counted for Hacktoberfest @biplobsd

**Comment by unicodeveloper** [comment]
I think those PRs were not given those labels.

**Comment by unicodeveloper** [comment]
Please don't send in any new PRs with you adjusting space. It's also why we like to assign issues so that we know the issues that should be worked on or not.

**Pull request merged**
