### PR TITLE
Fixed issue highlighting the DOTNET/C# code snippet

### PR DESCRIPTION
**Pull request by shelar1423**
## There is issue where the DOTNET/C# code snippet is not highlighted in the SDK's section of server ,while all other code snippets are.

# issue screenshots :
image

# FIX screenshot:
image

### CODE REVIEW

**Comment by shelar1423** [comment]
@unicodeveloper kindly have a review.

**Comment by sumitsaurabh927** [comment]
Hey @shelar1423 please wait for the review!

**Comment by shelar1423** [comment]
yeah @sumitsaurabh927 waiting for @unicodeveloper

**Comment by shelar1423** [comment]
@scopsy kindly have a review

**Review by unicodeveloper — APPROVED** [review]

**Pull request merged**
