### PR TITLE
fix: update Java examples in the API Reference docs for Events and Subscribers Endpoints

### PR DESCRIPTION
**Pull request by m-a-r-1912**
For this issue: [295](https://github.com/novuhq/docs/issues/295)
This draft PR is to show the progress of updating the API Reference docs for Java. 
The Events methods have been updated and I'll continue to add more updated docs.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Hello @m-a-r-1912 Please do you have any update for this? It has been in draft mode for a week now

**Comment by m-a-r-1912** [comment]
Yes! I'll add my updates today.

**Comment by unicodeveloper** [comment]
Thanks for adding the updates. Are there other updates you want to add this current PR? If not, can you remove it from DRAFT? @m-a-r-1912

**Comment by m-a-r-1912** [comment]
The Java example changes for the Events and Subscribers endpoints should be good to review now. I didn't update all of the Subscribers Java examples because either the SDK method seemed to cause errors with the Novu API or there isn't an equivalent SDK method for the endpoint.

**Review by unicodeveloper — APPROVED** [review]

**Pull request merged**
