### PR TITLE
new info & refactoring: Added a tables for all the dynamic variables [ticket DVRL-37]

### PR DESCRIPTION
**Pull request by iampearceman**
1. Added the definition of `actor` to the glossary.
2. Updated the "Overview" page of the content creation section.
3. Added tables with types and definitions for all the variables users can use within our workflow editor.
4. Separation of the glossary and the additional educational resources
5. Small changes and fixes.

### CODE REVIEW

**Comment by iampearceman** [comment]
Review and merge this pull request: [Link](https://github.com/novuhq/docs/pull/353)

To resolve the conflicts.

**Comment by unicodeveloper** [comment]
@iampearceman You still need to resolve the conflicts

**Review by unicodeveloper — APPROVED** [review]

**Comment by unicodeveloper** [comment]
@iampearceman Great work. One more thing, there's no code sample or explanation of how to use actor variables in the email/in-app/push etc editor in this PR. What I can see is the actor definition and glossary

**Comment by iampearceman** [comment]
> @iampearceman Great work.
> 
> One more thing, there's no code sample or explanation of how to use actor variables in the email/in-app/push etc editor in this PR. What I can see is the actor definition and glossary. I'll like to see practical examples in form of editor gifs or code.

My next PR will be for that.

**Pull request merged**
